<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lessons')->insert([
            [
                'id' => 1,
                'learning_track_id' => 1,
                'code' => 'LESSON_PREP_001',
                'slug' => 'hanja-structure-basics',
                'title' => '한자 구조와 획 맛보기',
                'objective' => '한자를 처음 보는 학습자가 획과 구조를 낯설지 않게 느끼도록 한다.',
                'summary' => '좌우형/상하형과 기본 획 감각을 잡는다.',
                'lesson_type' => 'concept',
                'difficulty_level' => 1,
                'estimated_minutes' => 12,
                'unlock_rule_json' => json_encode(['requires' => []]),
                'sort_order' => 1,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'learning_track_id' => 1,
                'code' => 'LESSON_PREP_002',
                'slug' => 'basic-stroke-flow',
                'title' => '필순 감각 익히기',
                'objective' => '정답 집착보다 큰 흐름으로 글자를 따라 쓰는 감각을 익힌다.',
                'summary' => '쓰기 연습 전 준비 레슨',
                'lesson_type' => 'practice',
                'difficulty_level' => 1,
                'estimated_minutes' => 10,
                'unlock_rule_json' => json_encode(['requires' => ['LESSON_PREP_001']]),
                'sort_order' => 2,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'learning_track_id' => 2,
                'code' => 'LESSON_FIVE_001',
                'slug' => 'five-elements-overview',
                'title' => '오행 5글자 전체보기',
                'objective' => '목·화·토·금·수 한자를 보고 사주 연결 이미지를 만든다.',
                'summary' => '오행 5글자 입문 레슨',
                'lesson_type' => 'hanja_card',
                'difficulty_level' => 1,
                'estimated_minutes' => 15,
                'unlock_rule_json' => json_encode(['requires' => ['LESSON_PREP_001']]),
                'sort_order' => 1,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'learning_track_id' => 3,
                'code' => 'LESSON_STEM_001',
                'slug' => 'heavenly-stems-overview',
                'title' => '천간 10글자 입문',
                'objective' => '갑을병정무기경신임계의 순서와 오행 연결을 읽는다.',
                'summary' => '천간 전체 입문',
                'lesson_type' => 'hanja_card',
                'difficulty_level' => 2,
                'estimated_minutes' => 18,
                'unlock_rule_json' => json_encode(['requires' => ['LESSON_FIVE_001']]),
                'sort_order' => 1,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'learning_track_id' => 4,
                'code' => 'LESSON_BRANCH_001',
                'slug' => 'earthly-branches-overview',
                'title' => '지지 12글자 입문',
                'objective' => '자축인묘진사오미신유술해를 동물·시간감각과 함께 익힌다.',
                'summary' => '지지 전체 입문',
                'lesson_type' => 'hanja_card',
                'difficulty_level' => 2,
                'estimated_minutes' => 20,
                'unlock_rule_json' => json_encode(['requires' => ['LESSON_STEM_001']]),
                'sort_order' => 1,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'learning_track_id' => 5,
                'code' => 'LESSON_CHART_001',
                'slug' => 'four-pillars-first-look',
                'title' => '연주·월주·일주·시주 읽기',
                'objective' => '만세력 표의 8글자를 보고 어디가 연/월/일/시인지 구분한다.',
                'summary' => '첫 실전 입문',
                'lesson_type' => 'example_chart',
                'difficulty_level' => 2,
                'estimated_minutes' => 15,
                'unlock_rule_json' => json_encode(['requires' => ['LESSON_BRANCH_001']]),
                'sort_order' => 1,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('lesson_steps')->insert([
            // Lesson 1 steps
            [
                'id' => 1,
                'lesson_id' => 1,
                'step_type' => 'intro',
                'title' => '한자는 그림이 아니라 부품이다',
                'content_markdown' => '한자는 한 번에 통으로 외우기보다 **획 + 구조 + 반복 노출**로 익히는 것이 훨씬 쉽습니다.',
                'payload_json' => json_encode(['cta' => '다음 단계로']),
                'sort_order' => 1,
                'is_required' => true,
                'estimated_minutes' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'lesson_id' => 1,
                'step_type' => 'explanation',
                'title' => '좌우형과 상하형 감각 익히기',
                'content_markdown' => '좌우형은 양쪽으로, 상하형은 위아래로 무게가 나뉩니다. 글자의 **골격**을 먼저 본다고 생각하면 됩니다.',
                'payload_json' => json_encode(['examples' => ['木', '苗', '字']]),
                'sort_order' => 2,
                'is_required' => true,
                'estimated_minutes' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'lesson_id' => 1,
                'step_type' => 'summary',
                'title' => '이 레슨의 핵심',
                'content_markdown' => '정확히 예쁘게 쓰기보다 **어디서 시작하고 어떻게 흘러가는지** 보는 습관을 만든다.',
                'payload_json' => json_encode(['keywords' => ['획', '구조', '반복']]),
                'sort_order' => 3,
                'is_required' => true,
                'estimated_minutes' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lesson 2 steps
            [
                'id' => 4,
                'lesson_id' => 2,
                'step_type' => 'stroke_order',
                'title' => '큰 흐름으로 따라 쓰기',
                'content_markdown' => '정교한 필적 채점보다 **끊김 없이 흐름을 따라가는 것**에 집중합니다.',
                'payload_json' => json_encode(['practice_mode' => 'trace']),
                'sort_order' => 1,
                'is_required' => true,
                'estimated_minutes' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'lesson_id' => 2,
                'step_type' => 'guided_practice',
                'title' => '가이드 위에 써보기',
                'content_markdown' => '희미한 가이드 선을 따라 3번씩 써보세요.',
                'payload_json' => json_encode(['repeat_count' => 3]),
                'sort_order' => 2,
                'is_required' => true,
                'estimated_minutes' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lesson 3 steps
            [
                'id' => 6,
                'lesson_id' => 3,
                'step_type' => 'intro',
                'title' => '오행은 사주의 색연필 통이다',
                'content_markdown' => '목·화·토·금·수는 뒤에서 천간과 지지를 읽을 때 계속 등장하는 핵심 분류입니다.',
                'payload_json' => json_encode(['focus' => ['木', '火', '土', '金', '水']]),
                'sort_order' => 1,
                'is_required' => true,
                'estimated_minutes' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'lesson_id' => 3,
                'step_type' => 'explanation',
                'title' => '오행 5글자 연결하기',
                'content_markdown' => '글자를 외울 때는 **뜻 + 사주 역할 + 색감**을 같이 묶어두면 훨씬 오래 갑니다.',
                'payload_json' => json_encode(['display_mode' => 'card_grid']),
                'sort_order' => 2,
                'is_required' => true,
                'estimated_minutes' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'lesson_id' => 3,
                'step_type' => 'quiz',
                'title' => '오행 확인 퀴즈',
                'content_markdown' => '오행 5글자를 보고 뜻과 오행을 매칭합니다.',
                'payload_json' => json_encode(['quiz_set_code' => 'QUIZ_FIVE_001']),
                'sort_order' => 3,
                'is_required' => true,
                'estimated_minutes' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lesson 4 steps
            [
                'id' => 9,
                'lesson_id' => 4,
                'step_type' => 'intro',
                'title' => '천간 10글자는 하늘쪽 코드다',
                'content_markdown' => '갑을병정무기경신임계는 사주에서 **위줄**에 자주 보게 되는 핵심 글자입니다.',
                'payload_json' => json_encode(['focus' => ['甲', '乙', '丙', '丁', '戊', '己', '庚', '辛', '壬', '癸']]),
                'sort_order' => 1,
                'is_required' => true,
                'estimated_minutes' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'lesson_id' => 4,
                'step_type' => 'explanation',
                'title' => '오행과 음양 붙여 보기',
                'content_markdown' => '천간은 오행뿐 아니라 **음/양** 감각까지 같이 보면 기억이 빠릅니다.',
                'payload_json' => json_encode(['display_mode' => 'sequence']),
                'sort_order' => 2,
                'is_required' => true,
                'estimated_minutes' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lesson 5 steps
            [
                'id' => 11,
                'lesson_id' => 5,
                'step_type' => 'intro',
                'title' => '지지 12글자는 땅쪽 코드다',
                'content_markdown' => '자축인묘진사오미신유술해는 사주에서 **아래줄**에 자주 보게 되는 핵심 글자입니다.',
                'payload_json' => json_encode(['focus' => ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥']]),
                'sort_order' => 1,
                'is_required' => true,
                'estimated_minutes' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'lesson_id' => 5,
                'step_type' => 'explanation',
                'title' => '동물과 시간대 감각 붙이기',
                'content_markdown' => '지지는 동물·시간대·계절감을 같이 붙이면 기억이 훨씬 오래갑니다.',
                'payload_json' => json_encode(['display_mode' => 'grid']),
                'sort_order' => 2,
                'is_required' => true,
                'estimated_minutes' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lesson 6 steps
            [
                'id' => 13,
                'lesson_id' => 6,
                'step_type' => 'intro',
                'title' => '연월일시 먼저 자리를 읽는다',
                'content_markdown' => '해석보다 먼저, 표의 어느 칸이 연주·월주·일주·시주인지 위치를 읽을 줄 알아야 합니다.',
                'payload_json' => json_encode(['sample_chart_code' => 'EXAMPLE_CHART_001']),
                'sort_order' => 1,
                'is_required' => true,
                'estimated_minutes' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'lesson_id' => 6,
                'step_type' => 'summary',
                'title' => '오늘의 목표',
                'content_markdown' => '8글자를 무서워하지 않고 **칸과 글자**를 분리해서 보는 데 성공하면 됩니다.',
                'payload_json' => json_encode(['keywords' => ['연주', '월주', '일주', '시주']]),
                'sort_order' => 2,
                'is_required' => true,
                'estimated_minutes' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
