<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuizSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('quiz_sets')->insert([
            [
                'id' => 1,
                'lesson_id' => 3,
                'code' => 'QUIZ_FIVE_001',
                'title' => '오행 5글자 기본 퀴즈',
                'scope_type' => 'lesson',
                'description' => '오행 한자의 뜻과 오행 분류를 맞히는 기본 퀴즈',
                'difficulty_level' => 1,
                'pass_score' => 70,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'lesson_id' => 4,
                'code' => 'QUIZ_STEM_001',
                'title' => '천간 10글자 구별 퀴즈',
                'scope_type' => 'lesson',
                'description' => '천간의 오행과 음양을 연결해보는 퀴즈',
                'difficulty_level' => 2,
                'pass_score' => 70,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'lesson_id' => 5,
                'code' => 'QUIZ_BRANCH_001',
                'title' => '지지 12글자 기본 퀴즈',
                'scope_type' => 'lesson',
                'description' => '지지를 글자/동물/오행으로 연결하는 퀴즈',
                'difficulty_level' => 2,
                'pass_score' => 70,
                'publish_status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('quiz_items')->insert([
            // Quiz set 1 - 오행
            [
                'id' => 1,
                'quiz_set_id' => 1,
                'question_type' => 'multiple_choice',
                'prompt_text' => '木은 어떤 뜻인가요?',
                'target_hanja_char_id' => 1,
                'choices_json' => json_encode(['불', '흙', '나무', '물']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 2]),
                'explanation_text' => '木은 나무를 뜻하며 오행의 목에 해당합니다.',
                'hint_text' => '줄기와 가지 이미지를 떠올려보세요.',
                'sort_order' => 1,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'quiz_set_id' => 1,
                'question_type' => 'multiple_choice',
                'prompt_text' => '火의 오행은 무엇인가요?',
                'target_hanja_char_id' => 2,
                'choices_json' => json_encode(['wood', 'fire', 'earth', 'water']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 1]),
                'explanation_text' => '火는 오행 중 화입니다.',
                'hint_text' => '불꽃 이미지를 떠올려보세요.',
                'sort_order' => 2,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'quiz_set_id' => 1,
                'question_type' => 'multiple_choice',
                'prompt_text' => '金의 뜻으로 가장 가까운 것은?',
                'target_hanja_char_id' => 4,
                'choices_json' => json_encode(['쇠', '물', '나무', '흙']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 0]),
                'explanation_text' => '金은 쇠, 금속의 의미를 가집니다.',
                'hint_text' => '가을과 결단 이미지를 같이 붙이면 기억이 쉽습니다.',
                'sort_order' => 3,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'quiz_set_id' => 1,
                'question_type' => 'multiple_choice',
                'prompt_text' => '물에 해당하는 한자를 고르세요.',
                'target_hanja_char_id' => null,
                'choices_json' => json_encode(['木', '火', '水', '土']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 2]),
                'explanation_text' => '水가 물입니다.',
                'hint_text' => '흐르는 이미지!',
                'sort_order' => 4,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Quiz set 2 - 천간
            [
                'id' => 5,
                'quiz_set_id' => 2,
                'question_type' => 'multiple_choice',
                'prompt_text' => '甲의 오행은 무엇인가요?',
                'target_hanja_char_id' => 6,
                'choices_json' => json_encode(['wood', 'fire', 'earth', 'metal']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 0]),
                'explanation_text' => '甲은 양목입니다.',
                'hint_text' => '갑은 시작하는 나무입니다.',
                'sort_order' => 1,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'quiz_set_id' => 2,
                'question_type' => 'multiple_choice',
                'prompt_text' => '丁은 어떤 성향에 더 가까운가요?',
                'target_hanja_char_id' => 9,
                'choices_json' => json_encode(['양화', '음화', '양수', '음금']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 1]),
                'explanation_text' => '丁은 음화입니다.',
                'hint_text' => '촛불처럼 작고 선명한 불.',
                'sort_order' => 2,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'quiz_set_id' => 2,
                'question_type' => 'multiple_choice',
                'prompt_text' => '壬과 癸 중 큰 물에 더 가까운 글자는?',
                'target_hanja_char_id' => null,
                'choices_json' => json_encode(['壬', '癸']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 0]),
                'explanation_text' => '壬은 큰 물, 癸는 비나 이슬 같은 세밀한 물로 봅니다.',
                'hint_text' => '바다 vs 이슬.',
                'sort_order' => 3,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'quiz_set_id' => 2,
                'question_type' => 'true_false',
                'prompt_text' => '庚은 금(金)에 속한다.',
                'target_hanja_char_id' => 12,
                'choices_json' => null,
                'answer_payload_json' => json_encode(['correct_boolean' => true]),
                'explanation_text' => '庚은 양금입니다.',
                'hint_text' => '날이 선 금속 공구를 떠올려보세요.',
                'sort_order' => 4,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Quiz set 3 - 지지
            [
                'id' => 9,
                'quiz_set_id' => 3,
                'question_type' => 'multiple_choice',
                'prompt_text' => '子는 어떤 지지인가요?',
                'target_hanja_char_id' => 16,
                'choices_json' => json_encode(['자', '묘', '술', '해']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 0]),
                'explanation_text' => '子는 지지의 첫 글자 자입니다.',
                'hint_text' => '자축인묘의 맨 앞!',
                'sort_order' => 1,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'quiz_set_id' => 3,
                'question_type' => 'multiple_choice',
                'prompt_text' => '午의 오행은 무엇인가요?',
                'target_hanja_char_id' => 22,
                'choices_json' => json_encode(['wood', 'fire', 'earth', 'water']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 1]),
                'explanation_text' => '午는 화 기운을 대표하는 지지입니다.',
                'hint_text' => '정오의 태양을 떠올리면 쉽습니다.',
                'sort_order' => 2,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'quiz_set_id' => 3,
                'question_type' => 'multiple_choice',
                'prompt_text' => '가을의 금 기운과 가장 잘 연결되는 지지는?',
                'target_hanja_char_id' => null,
                'choices_json' => json_encode(['寅', '酉', '亥', '卯']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 1]),
                'explanation_text' => '酉는 가을의 금 기운과 연결됩니다.',
                'hint_text' => '수확과 정제의 이미지.',
                'sort_order' => 3,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'quiz_set_id' => 3,
                'question_type' => 'multiple_choice',
                'prompt_text' => '겨울의 깊은 물문 같은 지지는?',
                'target_hanja_char_id' => 27,
                'choices_json' => json_encode(['辰', '未', '亥', '巳']),
                'answer_payload_json' => json_encode(['correct_choice_index' => 2]),
                'explanation_text' => '亥는 겨울로 넘어가는 큰 물의 문처럼 이해할 수 있습니다.',
                'hint_text' => '해수(亥水) 기억!',
                'sort_order' => 4,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
